# Generated by Django 4.1.2 on 2022-10-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='sond_id',
            new_name='sond_ID',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artiste_ID',
        ),
    ]
